---
title: Caso de Uso
---

    flowchart LR
    
    actorCliente([Cliente])
    actorEmpleado([Empleado])
    actorAdministrador([Admimistador])

    casoReservar[Reservar]
    casoConsultarReserva[[Consultar Reserva]]
    casoSolicitarCancelacion[[Solicitar Cancelacion]]
    casoCrearCuenta[Crear Cuenta]
    casoConsultarInformacion[Consulata Informacion]
    casoGestionarCuenta[Gestionar Cuenta]
    
    casoPagar[[Pagar Reserva]]
    casoSolicitarBaja[[Solicitar Baja]]
    casoEliminarCuenta[Eliminar cuenta]
    casoViaje[[Viaje]]
    casoHotel[[Hotel]]
    casoAuto[[Auto]]

    casoGastionarReservas[Gestionar Reservas]
    casoModificarReservas[[Modificar Reservas]]
    casoConsultarReservas[[Consultar Reservas]]
    casoCancelarReserva[[Cancelar Reserva]]
    casoCabiarFecha[[Cambiar fecha]]
    

    casoPermisosCliente((Permisos Cliente))
    casoPermisosEmpleado((Permisos Empleado))
    casoPermisosAdministrador((Permisos Administrador))

    casoGestionarPermisos[Gestionar Permisos]
    casoGestionarPersonal[Gestionar Personal]
    casoAltaEmpleado[[Alta Empleado]]
     casoBajaEmpleado[[baja Empleado]]
    

    actorCliente -->  casoPermisosCliente
    actorEmpleado --> casoPermisosEmpleado
    actorAdministrador --> casoPermisosAdministrador
    
    actorEmpleado -->  casoPermisosCliente

    actorAdministrador --> casoPermisosCliente
    actorAdministrador --> casoPermisosEmpleado

    casoPermisosCliente --> casoCrearCuenta 
    casoCrearCuenta --> casoReservar
    casoReservar -.-> casoViaje -.-> casoPagar
        casoReservar -.-> casoHotel -.-> casoPagar
            casoReservar -.-> casoAuto -.-> casoPagar
    casoViaje -.-> casoSolicitarCancelacion
        casoHotel -.-> casoSolicitarCancelacion
            casoAuto -.-> casoSolicitarCancelacion
    casoPermisosCliente--> casoGestionarCuenta --> casoSolicitarBaja
    casoReservar --> casoConsultarReserva
    casoPermisosCliente --> casoConsultarInformacion
  

    casoPermisosEmpleado --> casoEliminarCuenta <--> casoSolicitarBaja
    casoPermisosEmpleado --> casoGastionarReservas 
    casoGastionarReservas --> casoModificarReservas
        casoModificarReservas --> casoCabiarFecha
        casoModificarReservas --> casoCancelarReserva <--> casoSolicitarCancelacion
    
        
    casoGastionarReservas --> casoConsultarReservas

    
    casoPermisosAdministrador --> casoGestionarPermisos
    casoPermisosAdministrador --> casoGestionarPersonal
        casoGestionarPersonal --> casoAltaEmpleado
        casoGestionarPersonal --> casoBajaEmpleado

